services:
  base:
    build:
      context: .
      target: pre_installed
      platforms:
      - linux/amd64
      - linux/arm64
    image: maayanlab/base:1.6.0
  basic:
    build:
      context: .
      target: basic
      platforms:
      - linux/amd64
      - linux/arm64
    image: maayanlab/base-basic:1.6.0
  python:
    build:
      context: .
      target: python
      platforms:
      - linux/amd64
      - linux/arm64
    image: maayanlab/base-python:1.6.0
