services:
  base:
    build:
      context: .
      target: pre_installed
    image: maayanlab/base:1.4.0
    platform: linux/amd64
  basic:
    build:
      context: .
      target: basic
    image: maayanlab/base-basic:1.4.0
    platform: linux/amd64
  python:
    build:
      context: .
      target: python
    image: maayanlab/base-python:1.4.0
    platform: linux/amd64
